### PR TITLE
feat: adding yaml schema for glossarist model v2

### LINKED ISSUE #30: Create the YAML Schema for glossarist v2 model
@HassanAkbar lets merge this first. Can you create the YAML Schema for this?

_Originally posted by @ronaldtse in https://github.com/glossarist/concept-model/issues/28#issuecomment-1689385470_

### PR DESCRIPTION
**Pull request by HassanAkbar**
Create the YAML Schema for glossarist v2 model

closes #30

### CODE REVIEW

**Comment by ronaldtse** [comment]
@HassanAkbar can you add the field description etc (and examples) to this schema file? Thanks!

**Review by ronaldtse — CHANGES_REQUESTED** [review]
Can you please help add field descriptions and examples? Also, add a workflow to render the YAML Schema into HTML documentation. Thanks!

**Comment by HassanAkbar** [comment]
> Can you please help add field descriptions and examples? Also, add a workflow to render the YAML Schema into HTML documentation. Thanks!

Sure, @ronaldtse I’m currently working on that.

**Comment by HassanAkbar** [comment]
@ronaldtse I've added description and examples to the `yaml schema` files.
To generate the html site through workflow, can I use [json-schema-for-humans](https://github.com/coveooss/json-schema-for-humans), or do you recommend some other tool for that?

**Comment by ronaldtse** [comment]
> @ronaldtse I've added description and examples to the `yaml schema` files.
> To generate the html site through workflow, can I use [json-schema-for-humans](https://github.com/coveooss/json-schema-for-humans), or do you recommend some other tool for that?

Yes of course, that's great. Thanks!

**Comment by HassanAkbar** [comment]
@ronaldtse Can you review this and let me know If we need to add something else in this PR?

Also, some keys in the schema are in `camel casing` and some are in `snake casing`, should I start implementing it in `glossarist` or should I wait for the finalization of the convention?

**Comment by ronaldtse** [comment]
@HassanAkbar let's do all snake case for the schema. We can add a duplicate schema with all camelcase.

**Comment by HassanAkbar** [comment]
@ronaldtse I've updated the PR to use `snake_casing` for attributes, it is now ready for review.

**Comment by ronaldtse** [comment]
This is good to go. Thank you @HassanAkbar !

Here's a followup task:
* [ ] Publish the concept model in a Metanorma document (Ribose flavor) that includes/links the two different schemas (and their versions in the future)

**Pull request merged**
