### PR TITLE
Use `lutaml` gem to generate the diagrams in this repo

### PR DESCRIPTION
**Pull request by w00lf**
#15, converted datamodel view files into lutaml syntax, added `relations` block to the view files, new diagrams

### CODE REVIEW

**Comment by ronaldtse** [comment]
Current issues:

Escaping of slashes:
image

Classes not bolded: (the two on top)
Screen Shot 2020-08-30 at 10 42 00 PM

Also, is it possible to change font style? We can use fontist to install the necessary font, e.g. Source Sans Pro.

**Comment by ronaldtse** [comment]
The `\<<` "Escaping of slashes" issue was a problem with input, now fixed. 

We also want to ensure we support  `<<namespace>> Classname` instead of requiring `'<<namespace>> Classname'` (with single quotes).

**Comment by ronaldtse** [comment]
Maybe we should use https://github.com/magjac/d3-graphviz since it allows more styling options.

**Comment by w00lf** [comment]
> The `\<<` "Escaping of slashes" issue was a problem with input, now fixed.
> 
> We also want to ensure we support `<<namespace>> Classname` instead of requiring `'<<namespace>> Classname'` (with single quotes).

Fixed, added support for attribute type namespace into lutaml

>Also, is it possible to change font style? We can use fontist to install the necessary font, e.g. Source Sans Pro.

I have added support for `fontname` into lutaml, we can use it to customize it as we want, also I have changed default font to `Helvetica` as in style.incl files

>Classes not bolded: (the two on top)

Fixed it, also added missing values for enums

**Comment by estubkjaer** [comment]
I support this suggestion by Ron, also because I/CaLAThe is using GraphViz

**Comment by ronaldtse** [comment]
Thanks @estubkjaer , we will be finding mechanisms to draw prettier diagrams, and hope that will also help CaLAThe!

**Pull request merged**
