### PR TITLE
[WIP] Glossarist model V2 documentation

### PR DESCRIPTION
**Pull request by HassanAkbar**
Initial documentation added for `glossarist model v2`

### CODE REVIEW

**Comment by HassanAkbar** [comment]
@ronaldtse This is how I've started to documentation of the `glossarist model v2` according to the files present in [metaverse-glossary](https://github.com/MetaverseStandards/metaversestandards-glossary/tree/main/msfglossary). 
There can be additional fields that are not present in the `meta verse-glossary` yet, I am currently looking at [isotc211-glossary](https://github.com/geolexica/isotc211-glossary/tree/main/geolexica) and will add the additional fields today in `localized-concepts`, but this is the general structure.

Should I continue like this? What do you suggest?

**Comment by ronaldtse** [comment]
@HassanAkbar you can continue like this or better yet, just use YAML schema and add in the documentation there.

**Comment by HassanAkbar** [comment]
@ronaldtse I've added the documentation for `isotc211-glossary` also. I've added all the fields that I could find in the [isotc211-glossary](https://github.com/geolexica/isotc211-glossary/tree/main/geolexica) repo. Can you give it a review?

**Comment by ronaldtse** [comment]
@HassanAkbar lets merge this first. Can you create the YAML Schema for this?

**Comment by HassanAkbar** [comment]
> @HassanAkbar lets merge this first. Can you create the YAML Schema for this?

@ronaldtse ~I'm not clear on what to do here. Can you elaborate on what do you mean by `create a YAML Schema` for this?~

Got it. Will continue on this in Issue #30

**Comment by ronaldtse** [comment]
YAML Schema refers to this:
https://asdf-standard.readthedocs.io/en/1.0.3/schemas/yaml_schema.html

**Pull request merged**
